services:
  fastapi:  # ← Это имя теперь используется для масштабирования
    image: ghcr.io/fvaganov/my-fastapi-image:1.0
    env_file: .env
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge